### ISSUE TITLE
can you add get Bulk because it doesn't exist in current bdcompat version and certain plugins need it to work

### ISSUE THREAD

**Issue by Cxsmo-ai** [strencher-kernel/bd-compat#10]
can you add get Bulk because it doesn't exist in current bdcompat version and certain plugins need it to work

**Comment by domi-btnr** [comment]
The API needs a rewrite anyways

**Comment by marioparaschiv** [comment]
> The API needs a rewrite anyways

Ours?

**Comment by domi-btnr** [comment]
Yes. `findModuleByProps` is deprecated in BD and the Plugin Devs will probably switch soon to the new Method which will break Plugins in bd-compat

**Comment by marioparaschiv** [comment]
That doesn't necessarily mean the API needs a rewrite. I'll add whatever is missing tomorrow.

**Comment by domi-btnr** [comment]
Yes, I didn't mean a rewrite. I am stupid. I mean the API would have to be updated for the new things

**Comment by Cxsmo-ai** [comment]
when is it going to get fixed just wondering
