### ISSUE TITLE
MessageLoggerV2 causes huge lag spikes.

### ISSUE THREAD

**Issue by NotSpaulding** [strencher-kernel/bd-compat#5]
[MessageLoggerV2 by Lighty](https://github.com/1Lighty/BetterDiscordPlugins/tree/master/Plugins/MessageLoggerV2) seems to be causing Discord huge lag spikes, seemingly randomly.

Discussed here first: https://discord.com/channels/891039687785996328/891053552947040306/929471135781900338.

**Comment by Strencher** [comment]
Shouldn't anymore, I think I fixed it already. Let me know if it still does.
