### ISSUE TITLE
Unknown error: undefined when saving files with SaveToRedux

### ISSUE THREAD

**Issue by eM-Krow** [strencher-kernel/bd-compat#9]
When attempting to use SaveToRedux in BCompat in Kernel the plugin errors and throws this:
![image](https://user-images.githubusercontent.com/87371945/172262654-c0836baa-3399-40a4-9e4a-ae60ae4a6fee.png)

**Comment by Strencher** [comment]
Should be fixed.

**Comment by eM-Krow** [comment]
Confirmed to be fixed. Thanks again for your work.
